export const FONT_FAMILY = {
  Inter: 'Inter',
  EuclidCircularA: 'EuclidCircularA',
  HandMarker: 'HandMarker',
  Lobster: 'Lobster',
  Helvetica: 'Helvetica',
  Futura: 'Futura',
  Garamond: 'Garamond',
  FranklinGothic: 'FranklinGothic',
  Roboto: 'Roboto',
  Montserrat: 'Montserrat',
  Avenir: 'Avenir',
  PlayfairDisplay: 'PlayfairDisplay',
  Lato: 'Lato',
  OpenSans: 'OpenSans',
  BebasNeue: 'BebasNeue',
  Merriweather: 'Merriweather',
  Raleway: 'Raleway',
  SourceSansPro: 'SourceSansPro',
};

export const fontSource = {
  [FONT_FAMILY.Inter]: [
    require('../assets/fonts/Inter-Medium.ttf'),
    require('../assets/fonts/Inter-Black.ttf'),
    require('../assets/fonts/Inter-Bold.ttf'),
    require('../assets/fonts/Inter-ExtraBold.ttf'),
    require('../assets/fonts/Inter-ExtraLight.ttf'),
    require('../assets/fonts/Inter-Light.ttf'),
    require('../assets/fonts/Inter-Regular.ttf'),
    require('../assets/fonts/Inter-SemiBold.ttf'),
    require('../assets/fonts/Inter-Thin.ttf'),
  ],

  [FONT_FAMILY.EuclidCircularA]: [
    require('../assets/fonts/EuclidCircularA-BoldItalic.ttf'),
    require('../assets/fonts/EuclidCircularA-Bold.ttf'),
    require('../assets/fonts/EuclidCircularA-Italic.ttf'),
    require('../assets/fonts/EuclidCircularA-LightItalic.ttf'),
    require('../assets/fonts/EuclidCircularA-Light.ttf'),
    require('../assets/fonts/EuclidCircularA-MediumItalic.ttf'),
    require('../assets/fonts/EuclidCircularA-Medium.ttf'),
    require('../assets/fonts/EuclidCircularA-Regular.ttf'),
    require('../assets/fonts/EuclidCircularA-SemiBoldItalic.ttf'),
    require('../assets/fonts/EuclidCircularA-SemiBold.ttf'),
  ],
  [FONT_FAMILY.HandMarker]: [require('../assets/fonts/HandMarker.ttf')],

  [FONT_FAMILY.Montserrat]: [
    require('../assets/fonts/Montserrat-Black.ttf'),
    require('../assets/fonts/Montserrat-BlackItalic.ttf'),
    require('../assets/fonts/Montserrat-Bold.ttf'),
    require('../assets/fonts/Montserrat-BoldItalic.ttf'),
    require('../assets/fonts/Montserrat-ExtraBold.ttf'),
    require('../assets/fonts/Montserrat-ExtraBoldItalic.ttf'),
    require('../assets/fonts/Montserrat-ExtraLight.ttf'),
    require('../assets/fonts/Montserrat-ExtraLightItalic.ttf'),
    require('../assets/fonts/Montserrat-Italic.ttf'),
    require('../assets/fonts/Montserrat-Light.ttf'),
    require('../assets/fonts/Montserrat-LightItalic.ttf'),
    require('../assets/fonts/Montserrat-Medium.ttf'),
    require('../assets/fonts/Montserrat-MediumItalic.ttf'),
    require('../assets/fonts/Montserrat-Regular.ttf'),
    require('../assets/fonts/Montserrat-SemiBold.ttf'),
    require('../assets/fonts/Montserrat-SemiBoldItalic.ttf'),
    require('../assets/fonts/Montserrat-Thin.ttf'),
    require('../assets/fonts/Montserrat-ThinItalic.ttf'),
  ],
};
