export const FONT_FAMILY = {
  Inter: 'Inter',
  EuclidCircularA: 'EuclidCircularA',
  HandMarker: 'HandMarker',
  Lobster: 'Lobster',
  Helvetica: 'Helvetica',
  Futura: 'Futura',
  Garamond: 'Garamond',
  FranklinGothic: 'FranklinGothic',
  Roboto: 'Roboto',
  Montserrat: 'Montserrat',
  Avenir: 'Avenir',
  PlayfairDisplay: 'PlayfairDisplay',
  Lato: 'Lato',
  OpenSans: 'OpenSans',
  BebasNeue: 'BebasNeue',
  Merriweather: 'Merriweather',
  Raleway: 'Raleway',
  SourceSansPro: 'SourceSansPro',
  ExcelsiorOutline: 'ExcelsiorOutline',
  LuckiestGuy: 'LuckiestGuy',
  CherryBombOne: 'CherryBombOne',
  DOTCIRFUL: 'DOTCIRFUL',
};

export const fontSource = {
  [FONT_FAMILY.CherryBombOne]: [
    require('../assets/fonts/CherryBombOne-Regular.ttf'),
  ],

  [FONT_FAMILY.Inter]: [
    require('../assets/fonts/Inter-Medium.ttf'),
    require('../assets/fonts/Inter-Black.ttf'),
    require('../assets/fonts/Inter-Bold.ttf'),
    require('../assets/fonts/Inter-ExtraBold.ttf'),
    require('../assets/fonts/Inter-ExtraLight.ttf'),
    require('../assets/fonts/Inter-Light.ttf'),
    require('../assets/fonts/Inter-Regular.ttf'),
    require('../assets/fonts/Inter-SemiBold.ttf'),
    require('../assets/fonts/Inter-Thin.ttf'),
  ],

  [FONT_FAMILY.EuclidCircularA]: [
    require('../assets/fonts/EuclidCircularA-BoldItalic.ttf'),
    require('../assets/fonts/EuclidCircularA-Bold.ttf'),
    require('../assets/fonts/EuclidCircularA-Italic.ttf'),
    require('../assets/fonts/EuclidCircularA-LightItalic.ttf'),
    require('../assets/fonts/EuclidCircularA-Light.ttf'),
    require('../assets/fonts/EuclidCircularA-MediumItalic.ttf'),
    require('../assets/fonts/EuclidCircularA-Medium.ttf'),
    require('../assets/fonts/EuclidCircularA-Regular.ttf'),
    require('../assets/fonts/EuclidCircularA-SemiBoldItalic.ttf'),
    require('../assets/fonts/EuclidCircularA-SemiBold.ttf'),
  ],
  [FONT_FAMILY.HandMarker]: [require('../assets/fonts/HandMarker.ttf')],

  [FONT_FAMILY.Montserrat]: [
    require('../assets/fonts/Montserrat-Black.ttf'),
    require('../assets/fonts/Montserrat-BlackItalic.ttf'),
    require('../assets/fonts/Montserrat-Bold.ttf'),
    require('../assets/fonts/Montserrat-BoldItalic.ttf'),
    require('../assets/fonts/Montserrat-ExtraBold.ttf'),
    require('../assets/fonts/Montserrat-ExtraBoldItalic.ttf'),
    require('../assets/fonts/Montserrat-ExtraLight.ttf'),
    require('../assets/fonts/Montserrat-ExtraLightItalic.ttf'),
    require('../assets/fonts/Montserrat-Italic.ttf'),
    require('../assets/fonts/Montserrat-Light.ttf'),
    require('../assets/fonts/Montserrat-LightItalic.ttf'),
    require('../assets/fonts/Montserrat-Medium.ttf'),
    require('../assets/fonts/Montserrat-MediumItalic.ttf'),
    require('../assets/fonts/Montserrat-Regular.ttf'),
    require('../assets/fonts/Montserrat-SemiBold.ttf'),
    require('../assets/fonts/Montserrat-SemiBoldItalic.ttf'),
    require('../assets/fonts/Montserrat-Thin.ttf'),
    require('../assets/fonts/Montserrat-ThinItalic.ttf'),
  ],
  [FONT_FAMILY.Helvetica]: [
    require('../assets/fonts/Helvetica.ttf'),
    require('@assets/fonts/helvetica-rounded-bold.otf'),
    require('@assets/fonts/Helvetica-Oblique.ttf'),
    require('@assets/fonts/helvetica-light.ttf'),
    require('@assets/fonts/helvetica-compressed.otf'),
    require('@assets/fonts/Helvetica-BoldOblique.ttf'),
    require('@assets/fonts/Helvetica-Bold.ttf'),
  ],
  [FONT_FAMILY.Futura]: [
    require('@assets/fonts/futur.ttf'),
    require('@assets/fonts/Futura-Boldfont.ttf'),
    require('@assets/fonts/Futura-BoldItalicfont.ttf'),
    require('@assets/fonts/FuturaBook.ttf'),
    require('@assets/fonts/FuturaBook.ttf'),
    require('@assets/fonts/FuturaBook-Italic.ttf'),
    require('@assets/fonts/FuturaExtraBlack.ttf'),
    require('@assets/fonts/FuturaHeavy.ttf'),
    require('@assets/fonts/FuturaHeavy-Italic.ttf'),
    require('@assets/fonts/futura-lightBt.ttf'),
    require('@assets/fonts/Futura-Light.ttf'),
    require('@assets/fonts/FuturaLight-Italic.ttf'),
    require('@assets/fonts/futura-mediumcondensedBt.ttf'),
    require('@assets/fonts/FuturaMedium-Italic.ttf'),
    require('@assets/fonts/Futura-XBlkBT.ttf'),
    require('@assets/fonts/unicode.futurab.ttf'),
    require('@assets/fonts/unicode.futurabb.ttf'),
  ],
  [FONT_FAMILY.Garamond]: [require('@assets/fonts/garamond.ttf')],

  [FONT_FAMILY.FranklinGothic]: [
    require('@assets/fonts/fgwo.ttf'),
    require('@assets/fonts/FRANKGO.ttf'),
    require('@assets/fonts/FranklinGothicCondensed.ttf'),
    require('@assets/fonts/FranklinGothic.ttf'),
    require('@assets/fonts/FranklinGothicITALIC.ttf'),
  ],
  [FONT_FAMILY.Roboto]: [
    require('@assets/fonts/Roboto-Black.ttf'),
    require('@assets/fonts/Roboto-BlackItalic.ttf'),
    require('@assets/fonts/Roboto-Bold.ttf'),
    require('@assets/fonts/Roboto-BoldItalic.ttf'),
    require('@assets/fonts/Roboto-Italic.ttf'),
    require('@assets/fonts/Roboto-Light.ttf'),
    require('@assets/fonts/Roboto-LightItalic.ttf'),
    require('@assets/fonts/Roboto-Medium.ttf'),
    require('@assets/fonts/Roboto-MediumItalic.ttf'),
    require('@assets/fonts/Roboto-Regular.ttf'),
    require('@assets/fonts/Roboto-Thin.ttf'),
    require('@assets/fonts/Roboto-ThinItalic.ttf'),
  ],

  [FONT_FAMILY.Montserrat]: [
    require('@assets/fonts/Montserrat-Black.ttf'),
    require('@assets/fonts/Montserrat-BlackItalic.ttf'),
    require('@assets/fonts/Montserrat-Bold.ttf'),
    require('@assets/fonts/Montserrat-BoldItalic.ttf'),
    require('@assets/fonts/Montserrat-ExtraBold.ttf'),
    require('@assets/fonts/Montserrat-ExtraBoldItalic.ttf'),
    require('@assets/fonts/Montserrat-ExtraLight.ttf'),
    require('@assets/fonts/Montserrat-ExtraLightItalic.ttf'),
    require('@assets/fonts/Montserrat-Italic.ttf'),
    require('@assets/fonts/Montserrat-Light.ttf'),
    require('@assets/fonts/Montserrat-LightItalic.ttf'),
    require('@assets/fonts/Montserrat-Medium.ttf'),
    require('@assets/fonts/Montserrat-MediumItalic.ttf'),
    require('@assets/fonts/Montserrat-Regular.ttf'),
    require('@assets/fonts/Montserrat-SemiBold.ttf'),
    require('@assets/fonts/Montserrat-SemiBoldItalic.ttf'),
    require('@assets/fonts/Montserrat-Thin.ttf'),
    require('@assets/fonts/Montserrat-ThinItalic.ttf'),
  ],

  [FONT_FAMILY.Avenir]: [
    require('@assets/fonts/AvenirLTProRoman.otf'),
    require('@assets/fonts/AvenirLTProOblique.otf'),
    require('@assets/fonts/AvenirLTProMediumOblique.otf'),
    require('@assets/fonts/AvenirLTProLightOblique.otf'),
    require('@assets/fonts/AvenirLTProMedium.otf'),
    require('@assets/fonts/AvenirLTProLight.otf'),
    require('@assets/fonts/AvenirLTProHeavy.otf'),
    require('@assets/fonts/AvenirLTProHeavyOblique.otf'),
    require('@assets/fonts/AvenirLTProBookOblique.otf'),
    require('@assets/fonts/AvenirLTProBook.otf'),
    require('@assets/fonts/AvenirLTProBlackOblique.otf'),
    require('@assets/fonts/AvenirLTProBlack.otf'),
  ],
  [FONT_FAMILY.PlayfairDisplay]: [
    require('@assets/fonts/PlayfairDisplay-VariableFont_wght.ttf'),
    require('@assets/fonts/PlayfairDisplay-SemiBoldItalic.ttf'),
    require('@assets/fonts/PlayfairDisplay-SemiBold.ttf'),
    require('@assets/fonts/PlayfairDisplay-Regular.ttf'),
    require('@assets/fonts/PlayfairDisplay-MediumItalic.ttf'),
    require('@assets/fonts/PlayfairDisplay-Medium.ttf'),
    require('@assets/fonts/PlayfairDisplay-Italic.ttf'),
    require('@assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf'),
    require('@assets/fonts/PlayfairDisplay-ExtraBoldItalic.ttf'),
    require('@assets/fonts/PlayfairDisplay-ExtraBold.ttf'),
    require('@assets/fonts/PlayfairDisplay-BoldItalic.ttf'),
    require('@assets/fonts/PlayfairDisplay-Bold.ttf'),
    require('@assets/fonts/PlayfairDisplay-BlackItalic.ttf'),
    require('@assets/fonts/PlayfairDisplay-Black.ttf'),
  ],
  [FONT_FAMILY.Lato]: [
    require('@assets/fonts/Lato-ThinItalic.ttf'),
    require('@assets/fonts/Lato-Thin.ttf'),
    require('@assets/fonts/Lato-Regular.ttf'),
    require('@assets/fonts/Lato-LightItalic.ttf'),
    require('@assets/fonts/Lato-Light.ttf'),
    require('@assets/fonts/Lato-Italic.ttf'),
    require('@assets/fonts/Lato-BoldItalic.ttf'),
    require('@assets/fonts/Lato-Bold.ttf'),
    require('@assets/fonts/Lato-BlackItalic.ttf'),
    require('@assets/fonts/Lato-Black.ttf'),
  ],
  [FONT_FAMILY.OpenSans]: [
    require('@assets/fonts/OpenSans-VariableFont.ttf'),
    require('@assets/fonts/OpenSans-SemiBoldItalic.ttf'),
    require('@assets/fonts/OpenSans-SemiBold.ttf'),
    require('@assets/fonts/OpenSans-Regular.ttf'),
    require('@assets/fonts/OpenSans-Medium.ttf'),
    require('@assets/fonts/OpenSans-MediumItalic.ttf'),
    require('@assets/fonts/OpenSans-LightItalic.ttf'),
    require('@assets/fonts/OpenSans-Light.ttf'),
    require('@assets/fonts/OpenSans-Italic.ttf'),
    require('@assets/fonts/OpenSans-Italic-VariableFont_wdth.ttf'),
    require('@assets/fonts/OpenSans-ExtraBoldItalic.ttf'),
    require('@assets/fonts/OpenSans-ExtraBold.ttf'),
    require('@assets/fonts/OpenSans-BoldItalic.ttf'),
    require('@assets/fonts/OpenSans-Bold.ttf'),
    require('@assets/fonts/OpenSans_Condensed-Bold.ttf'),
    require('@assets/fonts/OpenSans_Condensed-BoldItalic.ttf'),
    require('@assets/fonts/OpenSans_Condensed-ExtraBold.ttf'),
    require('@assets/fonts/OpenSans_Condensed-ExtraBoldItalic.ttf'),
    require('@assets/fonts/OpenSans_Condensed-Italic.ttf'),
    require('@assets/fonts/OpenSans_Condensed-LightItalic.ttf'),
    require('@assets/fonts/OpenSans_Condensed-Light.ttf'),
    require('@assets/fonts/OpenSans_Condensed-Medium.ttf'),
    require('@assets/fonts/OpenSans_Condensed-MediumItalic.ttf'),
    require('@assets/fonts/OpenSans_Condensed-Regular.ttf'),
    require('@assets/fonts/OpenSans_Condensed-SemiBold.ttf'),
    require('@assets/fonts/OpenSans_Condensed-SemiBoldItalic.ttf'),

    require('@assets/fonts/OpenSans_SemiCondensed-Bold.ttf'),
    require('@assets/fonts/OpenSans_SemiCondensed-BoldItalic.ttf'),
    require('@assets/fonts/OpenSans_SemiCondensed-ExtraBold.ttf'),
    require('@assets/fonts/OpenSans_SemiCondensed-ExtraBoldItalic.ttf'),
    require('@assets/fonts/OpenSans_SemiCondensed-Italic.ttf'),
    require('@assets/fonts/OpenSans_SemiCondensed-Light.ttf'),
    require('@assets/fonts/OpenSans_SemiCondensed-LightItalic.ttf'),
    require('@assets/fonts/OpenSans_SemiCondensed-Medium.ttf'),
    require('@assets/fonts/OpenSans_SemiCondensed-MediumItalic.ttf'),
    require('@assets/fonts/OpenSans_SemiCondensed-Regular.ttf'),
    require('@assets/fonts/OpenSans_SemiCondensed-SemiBold.ttf'),
    require('@assets/fonts/OpenSans_SemiCondensed-SemiBoldItalic.ttf'),
  ],

  [FONT_FAMILY.BebasNeue]: [require('@assets/fonts/BebasNeue-Regular.ttf')],
  [FONT_FAMILY.Merriweather]: [
    require('@assets/fonts/Merriweather-Regular.ttf'),
    require('@assets/fonts/Merriweather-LightItalic.ttf'),
    require('@assets/fonts/Merriweather-Light.ttf'),
    require('@assets/fonts/Merriweather-Italic.ttf'),
    require('@assets/fonts/Merriweather-BoldItalic.ttf'),
    require('@assets/fonts/Merriweather-Bold.ttf'),
    require('@assets/fonts/Merriweather-BlackItalic.ttf'),
    require('@assets/fonts/Merriweather-Black.ttf'),
  ],
  [FONT_FAMILY.Raleway]: [
    require('@assets/fonts/Raleway-VariableFont_wght.ttf'),
    require('@assets/fonts/Raleway-ThinItalic.ttf'),
    require('@assets/fonts/Raleway-Thin.ttf'),
    require('@assets/fonts/Raleway-SemiBoldItalic.ttf'),
    require('@assets/fonts/Raleway-SemiBold.ttf'),
    require('@assets/fonts/Raleway-Regular.ttf'),
    require('@assets/fonts/Raleway-MediumItalic.ttf'),
    require('@assets/fonts/Raleway-Medium.ttf'),
    require('@assets/fonts/Raleway-LightItalic.ttf'),
    require('@assets/fonts/Raleway-Light.ttf'),
    require('@assets/fonts/Raleway-Italic.ttf'),
    require('@assets/fonts/Raleway-Italic-VariableFont_wght.ttf'),
    require('@assets/fonts/Raleway-ExtraLightItalic.ttf'),
    require('@assets/fonts/Raleway-ExtraLight.ttf'),
    require('@assets/fonts/Raleway-ExtraBoldItalic.ttf'),
    require('@assets/fonts/Raleway-ExtraBold.ttf'),
    require('@assets/fonts/Raleway-BoldItalic.ttf'),
    require('@assets/fonts/Raleway-Bold.ttf'),
    require('@assets/fonts/Raleway-BlackItalic.ttf'),
    require('@assets/fonts/Raleway-Black.ttf'),
  ],

  [FONT_FAMILY.SourceSansPro]: [
    require('@assets/fonts/SourceSansPro-SemiboldIt.otf'),
    require('@assets/fonts/SourceSansPro-Semibold.otf'),
    require('@assets/fonts/SourceSansPro-Regular.otf'),
    require('@assets/fonts/SourceSansPro-Light.otf'),
    require('@assets/fonts/SourceSansPro-LightIt.otf'),
    require('@assets/fonts/SourceSansPro-It.otf'),
    require('@assets/fonts/SourceSansPro-ExtraLightIt.otf'),
    require('@assets/fonts/SourceSansPro-ExtraLight.otf'),
    require('@assets/fonts/SourceSansPro-BoldIt.otf'),
    require('@assets/fonts/SourceSansPro-Bold.otf'),
    require('@assets/fonts/SourceSansPro-BlackIt.otf'),
    require('@assets/fonts/SourceSansPro-Black.otf'),
  ],

  [FONT_FAMILY.ExcelsiorOutline]: [
    require('@assets/fonts/ExcelsiorOutline.ttf'),
  ],

  [FONT_FAMILY.LuckiestGuy]: [require('@assets/fonts/LuckiestGuy-Regular.ttf')],

  [FONT_FAMILY.DOTCIRFUL]: [
    require('../assets/fonts/DOTCIRFUL-Bold.otf'),
    require('../assets/fonts/DOTCIRFUL-BoldItalic.otf'),
    require('../assets/fonts/DOTCIRFUL-Regular.otf'),
    require('../assets/fonts/DOTCIRFUL-RegularItalic.otf'),
  ],
};
