export const languages_best = [
  {
    label: 'English (Global English)',
    code: 'en',
    model: 'best',
    country_code: 'GB',
  },
  {
    label: 'English (Australia)',
    code: 'en_au',
    model: 'best',
    country_code: 'AU',
  },
  {
    label: 'English (United Kingdom)',
    code: 'en_uk',
    model: 'best',
    country_code: 'GB',
  },
  {
    label: 'English (United States)',
    code: 'en_us',
    model: 'best',
    country_code: 'US',
  },
  {label: 'Spanish (Español)', code: 'es', model: 'best', country_code: 'ES'},
  {label: 'French (Français)', code: 'fr', model: 'best', country_code: 'FR'},
  {label: 'German (Deutsch)', code: 'de', model: 'best', country_code: 'DE'},
  {label: 'Italian (Italiano)', code: 'it', model: 'best', country_code: 'IT'},
  {
    label: 'Portuguese (Português)',
    code: 'pt',
    model: 'best',
    country_code: 'PT',
  },
  {label: 'Dutch (Nederlands)', code: 'nl', model: 'best', country_code: 'NL'},
  {label: 'Hindi (हिन्दी)', code: 'hi', model: 'best', country_code: 'IN'},
  {label: 'Japanese (日本語)', code: 'ja', model: 'best', country_code: 'JP'},
  {label: 'Chinese (中文)', code: 'zh', model: 'best', country_code: 'CN'},
  {label: 'Finnish (Suomi)', code: 'fi', model: 'best', country_code: 'FI'},
  {label: 'Korean (한국어)', code: 'ko', model: 'best', country_code: 'KR'},
  {label: 'Polish (Polski)', code: 'pl', model: 'best', country_code: 'PL'},
  {label: 'Russian (Русский)', code: 'ru', model: 'best', country_code: 'RU'},
  {label: 'Turkish (Türkçe)', code: 'tr', model: 'best', country_code: 'TR'},
  {
    label: 'Ukrainian (Українська)',
    code: 'uk',
    model: 'best',
    country_code: 'UA',
  },
  {
    label: 'Vietnamese (Tiếng Việt)',
    code: 'vi',
    model: 'best',
    country_code: 'VN',
  },
];

export const languages_nano = [
  {
    label: 'Afrikaans (Afrikaans)',
    code: 'af',
    model: 'nano',
    country_code: 'ZA',
  },
  {label: 'Albanian (Shqip)', code: 'sq', model: 'nano', country_code: 'AL'},
  {label: 'Amharic (አማርኛ)', code: 'am', model: 'nano', country_code: 'ET'},
  {label: 'Arabic (العربية)', code: 'ar', model: 'nano', country_code: 'AE'},
  {label: 'Armenian (Հայերեն)', code: 'hy', model: 'nano', country_code: 'AM'},
  {label: 'Assamese (অসমীয়া)', code: 'as', model: 'nano', country_code: 'IN'},
  {
    label: 'Azerbaijani (Azərbaycanca)',
    code: 'az',
    model: 'nano',
    country_code: 'AZ',
  },
  {label: 'Bashkir (Башҡорт)', code: 'ba', model: 'nano', country_code: 'RU'},
  {label: 'Basque (Euskara)', code: 'eu', model: 'nano', country_code: 'ES'},
  {
    label: 'Belarusian (Беларуская)',
    code: 'be',
    model: 'nano',
    country_code: 'BY',
  },
  {label: 'Bengali (বাংলা)', code: 'bn', model: 'nano', country_code: 'BD'},
  {label: 'Bosnian (Bosanski)', code: 'bs', model: 'nano', country_code: 'BA'},
  {label: 'Breton (Brezhoneg)', code: 'br', model: 'nano', country_code: 'FR'},
  {
    label: 'Bulgarian (Български)',
    code: 'bg',
    model: 'nano',
    country_code: 'BG',
  },
  {label: 'Burmese (ဗမာစာ)', code: 'my', model: 'nano', country_code: 'MM'},
  {label: 'Catalan (Català)', code: 'ca', model: 'nano', country_code: 'ES'},
  {label: 'Croatian (Hrvatski)', code: 'hr', model: 'nano', country_code: 'HR'},
  {label: 'Czech (Čeština)', code: 'cs', model: 'nano', country_code: 'CZ'},
  {label: 'Danish (Dansk)', code: 'da', model: 'nano', country_code: 'DK'},
  {label: 'Estonian (Eesti)', code: 'et', model: 'nano', country_code: 'EE'},
  {label: 'Faroese (Føroyskt)', code: 'fo', model: 'nano', country_code: 'FO'},
  {label: 'Galician (Galego)', code: 'gl', model: 'nano', country_code: 'ES'},
  {label: 'Georgian (ქართული)', code: 'ka', model: 'nano', country_code: 'GE'},
  {label: 'Greek (Ελληνικά)', code: 'el', model: 'nano', country_code: 'GR'},
  {label: 'Gujarati (ગુજરાતી)', code: 'gu', model: 'nano', country_code: 'IN'},
  {
    label: 'Haitian (Kreyòl Ayisyen)',
    code: 'ht',
    model: 'nano',
    country_code: 'HT',
  },
  {label: 'Hausa (Hausa)', code: 'ha', model: 'nano', country_code: 'NG'},
  {
    label: 'Hawaiian (ʻŌlelo Hawaiʻi)',
    code: 'haw',
    model: 'nano',
    country_code: 'US',
  },
  {label: 'Hebrew (עברית)', code: 'he', model: 'nano', country_code: 'IL'},
  {label: 'Hungarian (Magyar)', code: 'hu', model: 'nano', country_code: 'HU'},
  {
    label: 'Icelandic (Íslenska)',
    code: 'is',
    model: 'nano',
    country_code: 'IS',
  },
  {
    label: 'Indonesian (Bahasa Indonesia)',
    code: 'id',
    model: 'nano',
    country_code: 'ID',
  },
  {
    label: 'Javanese (Basa Jawa)',
    code: 'jw',
    model: 'nano',
    country_code: 'ID',
  },
  {label: 'Kannada (ಕನ್ನಡ)', code: 'kn', model: 'nano', country_code: 'IN'},
  {label: 'Kazakh (Қазақ тілі)', code: 'kk', model: 'nano', country_code: 'KZ'},
  {label: 'Khmer (ខ្មែរ)', code: 'km', model: 'nano', country_code: 'KH'},
  {label: 'Lao (ລາວ)', code: 'lo', model: 'nano', country_code: 'LA'},
  {label: 'Latin (Latina)', code: 'la', model: 'nano', country_code: 'VA'},
  {label: 'Latvian (Latviešu)', code: 'lv', model: 'nano', country_code: 'LV'},
  {
    label: 'Lithuanian (Lietuvių)',
    code: 'lt',
    model: 'nano',
    country_code: 'LT',
  },
  {
    label: 'Luxembourgish (Lëtzebuergesch)',
    code: 'lb',
    model: 'nano',
    country_code: 'LU',
  },
  {
    label: 'Macedonian (Македонски)',
    code: 'mk',
    model: 'nano',
    country_code: 'MK',
  },
  {label: 'Malagasy (Malagasy)', code: 'mg', model: 'nano', country_code: 'MG'},
  {
    label: 'Malay (Bahasa Melayu)',
    code: 'ms',
    model: 'nano',
    country_code: 'MY',
  },
  {label: 'Malayalam (മലയാളം)', code: 'ml', model: 'nano', country_code: 'IN'},
  {label: 'Maltese (Malti)', code: 'mt', model: 'nano', country_code: 'MT'},
  {label: 'Maori (Māori)', code: 'mi', model: 'nano', country_code: 'NZ'},
  {label: 'Marathi (मराठी)', code: 'mr', model: 'nano', country_code: 'IN'},
  {label: 'Mongolian (Монгол)', code: 'mn', model: 'nano', country_code: 'MN'},
  {label: 'Nepali (नेपाली)', code: 'ne', model: 'nano', country_code: 'NP'},
  {label: 'Norwegian (Norsk)', code: 'no', model: 'nano', country_code: 'NO'},
  {
    label: 'Norwegian Nynorsk (Norsk Nynorsk)',
    code: 'nn',
    model: 'nano',
    country_code: 'NO',
  },
  {label: 'Occitan (Occitan)', code: 'oc', model: 'nano', country_code: 'FR'},
  {label: 'Panjabi (ਪੰਜਾਬੀ)', code: 'pa', model: 'nano', country_code: 'IN'},
  {label: 'Pashto (پښتو)', code: 'ps', model: 'nano', country_code: 'AF'},
  {label: 'Persian (فارسی)', code: 'fa', model: 'nano', country_code: 'IR'},
  {label: 'Romanian (Română)', code: 'ro', model: 'nano', country_code: 'RO'},
  {
    label: 'Sanskrit (संस्कृतम्)',
    code: 'sa',
    model: 'nano',
    country_code: 'IN',
  },
  {label: 'Serbian (Српски)', code: 'sr', model: 'nano', country_code: 'RS'},
  {label: 'Shona (Shona)', code: 'sn', model: 'nano', country_code: 'ZW'},
  {label: 'Sindhi (سنڌي)', code: 'sd', model: 'nano', country_code: 'PK'},
  {label: 'Sinhala (සිංහල)', code: 'si', model: 'nano', country_code: 'LK'},
  {label: 'Slovak (Slovenčina)', code: 'sk', model: 'nano', country_code: 'SK'},
  {
    label: 'Slovenian (Slovenščina)',
    code: 'sl',
    model: 'nano',
    country_code: 'SI',
  },
  {label: 'Somali (Soomaali)', code: 'so', model: 'nano', country_code: 'SO'},
  {
    label: 'Sundanese (Basa Sunda)',
    code: 'su',
    model: 'nano',
    country_code: 'ID',
  },
  {label: 'Swahili (Kiswahili)', code: 'sw', model: 'nano', country_code: 'KE'},
  {label: 'Swedish (Svenska)', code: 'sv', model: 'nano', country_code: 'SE'},
  {label: 'Tagalog (Tagalog)', code: 'tl', model: 'nano', country_code: 'PH'},
  {label: 'Tajik (Тоҷикӣ)', code: 'tg', model: 'nano', country_code: 'TJ'},
  {label: 'Tamil (தமிழ்)', code: 'ta', model: 'nano', country_code: 'IN'},
  {label: 'Tatar (татар)', code: 'tt', model: 'nano', country_code: 'RU'},
  {label: 'Telugu (తెలుగు)', code: 'te', model: 'nano', country_code: 'IN'},
  {label: 'Thai (ไทย)', code: 'th', model: 'nano', country_code: 'TH'},
  {label: 'Tibetan (བོད་ཡིག)', code: 'bo', model: 'nano', country_code: 'CN'},
  {label: 'Turkmen (Türkmen)', code: 'tk', model: 'nano', country_code: 'TM'},
  {label: 'Urdu (اردو)', code: 'ur', model: 'nano', country_code: 'PK'},
  {label: 'Uzbek (Oʻzbek)', code: 'uz', model: 'nano', country_code: 'UZ'},
  {label: 'Welsh (Cymraeg)', code: 'cy', model: 'nano', country_code: 'GB'},
  {label: 'Yiddish (ייִדיש)', code: 'yi', model: 'nano', country_code: 'IL'},
  {label: 'Yoruba (Yorùbá)', code: 'yo', model: 'nano', country_code: 'NG'},
];
