import {languageType} from 'components/LanguageSelector';

export const languages_best: languageType[] = [
  {
    label: 'English (Global English)',
    code: 'en',
    model: 'best',
    country_code: 'GB',
    short_label: 'English',
  },
  {
    label: 'English (Australia)',
    code: 'en_au',
    model: 'best',
    country_code: 'AU',
    short_label: 'English',
  },
  {
    label: 'English (United Kingdom)',
    code: 'en_uk',
    model: 'best',
    country_code: 'GB',
    short_label: 'English',
  },
  {
    label: 'English (United States)',
    code: 'en_us',
    model: 'best',
    country_code: 'US',
    short_label: 'English',
  },
  {
    label: 'Spanish (Español)',
    code: 'es',
    model: 'best',
    country_code: 'ES',
    short_label: 'Español',
  },
  {
    label: 'French (Français)',
    code: 'fr',
    model: 'best',
    country_code: 'FR',
    short_label: 'Français',
  },
  {
    label: 'German (Deutsch)',
    code: 'de',
    model: 'best',
    country_code: 'DE',
    short_label: 'Deutsch',
  },
  {
    label: 'Italian (Italiano)',
    code: 'it',
    model: 'best',
    country_code: 'IT',
    short_label: 'Italiano',
  },
  {
    label: 'Portuguese (Português)',
    code: 'pt',
    model: 'best',
    country_code: 'PT',
    short_label: 'Português',
  },
  {
    label: 'Dutch (Nederlands)',
    code: 'nl',
    model: 'best',
    country_code: 'NL',
    short_label: 'Nederlands',
  },
  {
    label: 'Hindi (हिन्दी)',
    code: 'hi',
    model: 'best',
    country_code: 'IN',
    short_label: 'हिन्दी',
  },
  {
    label: 'Japanese (日本語)',
    code: 'ja',
    model: 'best',
    country_code: 'JP',
    short_label: '日本語',
  },
  {
    label: 'Chinese (中文)',
    code: 'zh',
    model: 'best',
    country_code: 'CN',
    short_label: '中文',
  },
  {
    label: 'Finnish (Suomi)',
    code: 'fi',
    model: 'best',
    country_code: 'FI',
    short_label: 'Suomi',
  },
  {
    label: 'Korean (한국어)',
    code: 'ko',
    model: 'best',
    country_code: 'KR',
    short_label: '한국어',
  },
  {
    label: 'Polish (Polski)',
    code: 'pl',
    model: 'best',
    country_code: 'PL',
    short_label: 'Polski',
  },
  {
    label: 'Russian (Русский)',
    code: 'ru',
    model: 'best',
    country_code: 'RU',
    short_label: 'Русский',
  },
  {
    label: 'Turkish (Türkçe)',
    code: 'tr',
    model: 'best',
    country_code: 'TR',
    short_label: 'Türkçe',
  },
  {
    label: 'Ukrainian (Українська)',
    code: 'uk',
    model: 'best',
    country_code: 'UA',
    short_label: 'Українська',
  },
  {
    label: 'Vietnamese (Tiếng Việt)',
    code: 'vi',
    model: 'best',
    country_code: 'VN',
    short_label: 'Tiếng Việt',
  },
];

export const languages_nano: languageType[] = [
  {
    label: 'Afrikaans (Afrikaans)',
    code: 'af',
    model: 'nano',
    country_code: 'ZA',
    short_label: 'Afrikaans',
  },
  {
    label: 'Albanian (Shqip)',
    code: 'sq',
    model: 'nano',
    country_code: 'AL',
    short_label: 'Shqip',
  },
  {
    label: 'Amharic (አማርኛ)',
    code: 'am',
    model: 'nano',
    country_code: 'ET',
    short_label: 'አማርኛ',
  },
  {
    label: 'Arabic (العربية)',
    code: 'ar',
    model: 'nano',
    country_code: 'AE',
    short_label: 'العربية',
  },
  {
    label: 'Armenian (Հայերեն)',
    code: 'hy',
    model: 'nano',
    country_code: 'AM',
    short_label: 'Հայերեն',
  },
  {
    label: 'Assamese (অসমীয়া)',
    code: 'as',
    model: 'nano',
    country_code: 'IN',
    short_label: 'অসমীয়া',
  },
  {
    label: 'Azerbaijani (Azərbaycanca)',
    code: 'az',
    model: 'nano',
    country_code: 'AZ',
    short_label: 'Azərbaycanca',
  },
  {
    label: 'Bashkir (Башҡорт)',
    code: 'ba',
    model: 'nano',
    country_code: 'RU',
    short_label: 'Башҡорт',
  },
  {
    label: 'Basque (Euskara)',
    code: 'eu',
    model: 'nano',
    country_code: 'ES',
    short_label: 'Euskara',
  },
  {
    label: 'Belarusian (Беларуская)',
    code: 'be',
    model: 'nano',
    country_code: 'BY',
    short_label: 'Беларуская',
  },
  {
    label: 'Bengali (বাংলা)',
    code: 'bn',
    model: 'nano',
    country_code: 'BD',
    short_label: 'বাংলা',
  },
  {
    label: 'Bosnian (Bosanski)',
    code: 'bs',
    model: 'nano',
    country_code: 'BA',
    short_label: 'Bosanski',
  },
  {
    label: 'Breton (Brezhoneg)',
    code: 'br',
    model: 'nano',
    country_code: 'FR',
    short_label: 'Brezhoneg',
  },
  {
    label: 'Bulgarian (Български)',
    code: 'bg',
    model: 'nano',
    country_code: 'BG',
    short_label: 'Български',
  },
  {
    label: 'Burmese (ဗမာစာ)',
    code: 'my',
    model: 'nano',
    country_code: 'MM',
    short_label: 'ဗမာစာ',
  },
  {
    label: 'Catalan (Català)',
    code: 'ca',
    model: 'nano',
    country_code: 'ES',
    short_label: 'Català',
  },
  {
    label: 'Croatian (Hrvatski)',
    code: 'hr',
    model: 'nano',
    country_code: 'HR',
    short_label: 'Hrvatski',
  },
  {
    label: 'Czech (Čeština)',
    code: 'cs',
    model: 'nano',
    country_code: 'CZ',
    short_label: 'Čeština',
  },
  {
    label: 'Danish (Dansk)',
    code: 'da',
    model: 'nano',
    country_code: 'DK',
    short_label: 'Dansk',
  },
  {
    label: 'Estonian (Eesti)',
    code: 'et',
    model: 'nano',
    country_code: 'EE',
    short_label: 'Eesti',
  },
  {
    label: 'Faroese (Føroyskt)',
    code: 'fo',
    model: 'nano',
    country_code: 'FO',
    short_label: 'Føroyskt',
  },
  {
    label: 'Galician (Galego)',
    code: 'gl',
    model: 'nano',
    country_code: 'ES',
    short_label: 'Galego',
  },
  {
    label: 'Georgian (ქართული)',
    code: 'ka',
    model: 'nano',
    country_code: 'GE',
    short_label: 'ქართული',
  },
  {
    label: 'Greek (Ελληνικά)',
    code: 'el',
    model: 'nano',
    country_code: 'GR',
    short_label: 'Ελληνικά',
  },
  {
    label: 'Gujarati (ગુજરાતી)',
    code: 'gu',
    model: 'nano',
    country_code: 'IN',
    short_label: 'ગુજરાતી',
  },
  {
    label: 'Haitian (Kreyòl Ayisyen)',
    code: 'ht',
    model: 'nano',
    country_code: 'HT',
    short_label: 'Kreyòl Ayisyen',
  },
  {
    label: 'Hausa (Hausa)',
    code: 'ha',
    model: 'nano',
    country_code: 'NG',
    short_label: 'Hausa',
  },
  {
    label: 'Hawaiian (ʻŌlelo Hawaiʻi)',
    code: 'haw',
    model: 'nano',
    country_code: 'US',
    short_label: 'ʻŌlelo Hawaiʻi',
  },
  {
    label: 'Hebrew (עברית)',
    code: 'he',
    model: 'nano',
    country_code: 'IL',
    short_label: 'עברית',
  },
  {
    label: 'Hungarian (Magyar)',
    code: 'hu',
    model: 'nano',
    country_code: 'HU',
    short_label: 'Magyar',
  },
  {
    label: 'Icelandic (Íslenska)',
    code: 'is',
    model: 'nano',
    country_code: 'IS',
    short_label: 'Íslenska',
  },
  {
    label: 'Indonesian (Bahasa Indonesia)',
    code: 'id',
    model: 'nano',
    country_code: 'ID',
    short_label: 'Bahasa Indonesia',
  },
  {
    label: 'Javanese (Basa Jawa)',
    code: 'jw',
    model: 'nano',
    country_code: 'ID',
    short_label: 'Basa Jawa',
  },
  {
    label: 'Kannada (ಕನ್ನಡ)',
    code: 'kn',
    model: 'nano',
    country_code: 'IN',
    short_label: 'ಕನ್ನಡ',
  },
  {
    label: 'Kazakh (Қазақ тілі)',
    code: 'kk',
    model: 'nano',
    country_code: 'KZ',
    short_label: 'Қазақ тілі',
  },
  {
    label: 'Khmer (ខ្មែរ)',
    code: 'km',
    model: 'nano',
    country_code: 'KH',
    short_label: 'ខ្មែរ',
  },
  {
    label: 'Lao (ລາວ)',
    code: 'lo',
    model: 'nano',
    country_code: 'LA',
    short_label: 'ລາວ',
  },
  {
    label: 'Latin (Latina)',
    code: 'la',
    model: 'nano',
    country_code: 'VA',
    short_label: 'Latina',
  },
  {
    label: 'Latvian (Latviešu)',
    code: 'lv',
    model: 'nano',
    country_code: 'LV',
    short_label: 'Latviešu',
  },
  {
    label: 'Lithuanian (Lietuvių)',
    code: 'lt',
    model: 'nano',
    country_code: 'LT',
    short_label: 'Lietuvių',
  },
  {
    label: 'Luxembourgish (Lëtzebuergesch)',
    code: 'lb',
    model: 'nano',
    country_code: 'LU',
    short_label: 'Lëtzebuergesch',
  },
  {
    label: 'Macedonian (Македонски)',
    code: 'mk',
    model: 'nano',
    country_code: 'MK',
    short_label: 'Македонски',
  },
  {
    label: 'Malagasy (Malagasy)',
    code: 'mg',
    model: 'nano',
    country_code: 'MG',
    short_label: 'Malagasy',
  },
  {
    label: 'Malay (Bahasa Melayu)',
    code: 'ms',
    model: 'nano',
    country_code: 'MY',
    short_label: 'Bahasa Melayu',
  },
  {
    label: 'Malayalam (മലയാളം)',
    code: 'ml',
    model: 'nano',
    country_code: 'IN',
    short_label: 'മലയാളം',
  },
  {
    label: 'Maltese (Malti)',
    code: 'mt',
    model: 'nano',
    country_code: 'MT',
    short_label: 'Malti',
  },
  {
    label: 'Maori (Māori)',
    code: 'mi',
    model: 'nano',
    country_code: 'NZ',
    short_label: 'Māori',
  },
  {
    label: 'Marathi (मराठी)',
    code: 'mr',
    model: 'nano',
    country_code: 'IN',
    short_label: 'मराठी',
  },
  {
    label: 'Mongolian (Монгол)',
    code: 'mn',
    model: 'nano',
    country_code: 'MN',
    short_label: 'Монгол',
  },
  {
    label: 'Nepali (नेपाली)',
    code: 'ne',
    model: 'nano',
    country_code: 'NP',
    short_label: 'नेपाली',
  },
  {
    label: 'Norwegian (Norsk)',
    code: 'no',
    model: 'nano',
    country_code: 'NO',
    short_label: 'Norsk',
  },
  {
    label: 'Norwegian Nynorsk (Norsk Nynorsk)',
    code: 'nn',
    model: 'nano',
    country_code: 'NO',
    short_label: 'Norsk Nynorsk',
  },
  {
    label: 'Occitan (Occitan)',
    code: 'oc',
    model: 'nano',
    country_code: 'FR',
    short_label: 'Occitan',
  },
  {
    label: 'Panjabi (ਪੰਜਾਬੀ)',
    code: 'pa',
    model: 'nano',
    country_code: 'IN',
    short_label: 'ਪੰਜਾਬੀ',
  },
  {
    label: 'Pashto (پښتو)',
    code: 'ps',
    model: 'nano',
    country_code: 'AF',
    short_label: 'پښتو',
  },
  {
    label: 'Persian (فارسی)',
    code: 'fa',
    model: 'nano',
    country_code: 'IR',
    short_label: 'فارسی',
  },
  {
    label: 'Romanian (Română)',
    code: 'ro',
    model: 'nano',
    country_code: 'RO',
    short_label: 'Română',
  },
  {
    label: 'Sanskrit (संस्कृतम्)',
    code: 'sa',
    model: 'nano',
    country_code: 'IN',
    short_label: 'संस्कृतम्',
  },
  {
    label: 'Serbian (Српски)',
    code: 'sr',
    model: 'nano',
    country_code: 'RS',
    short_label: 'Српски',
  },
  {
    label: 'Shona (Shona)',
    code: 'sn',
    model: 'nano',
    country_code: 'ZW',
    short_label: 'Shona',
  },
  {
    label: 'Sindhi (سنڌي)',
    code: 'sd',
    model: 'nano',
    country_code: 'PK',
    short_label: 'سنڌي',
  },
  {
    label: 'Sinhala (සිංහල)',
    code: 'si',
    model: 'nano',
    country_code: 'LK',
    short_label: 'සිංහල',
  },
  {
    label: 'Slovak (Slovenčina)',
    code: 'sk',
    model: 'nano',
    country_code: 'SK',
    short_label: 'Slovenčina',
  },
  {
    label: 'Slovenian (Slovenščina)',
    code: 'sl',
    model: 'nano',
    country_code: 'SI',
    short_label: 'Slovenščina',
  },
  {
    label: 'Somali (Soomaali)',
    code: 'so',
    model: 'nano',
    country_code: 'SO',
    short_label: 'Soomaali',
  },
  {
    label: 'Sundanese (Basa Sunda)',
    code: 'su',
    model: 'nano',
    country_code: 'ID',
    short_label: 'Basa Sunda',
  },
  {
    label: 'Swahili (Kiswahili)',
    code: 'sw',
    model: 'nano',
    country_code: 'KE',
    short_label: 'Kiswahili',
  },
  {
    label: 'Swedish (Svenska)',
    code: 'sv',
    model: 'nano',
    country_code: 'SE',
    short_label: 'Svenska',
  },
  {
    label: 'Tagalog (Tagalog)',
    code: 'tl',
    model: 'nano',
    country_code: 'PH',
    short_label: 'Tagalog',
  },
  {
    label: 'Tajik (Тоҷикӣ)',
    code: 'tg',
    model: 'nano',
    country_code: 'TJ',
    short_label: 'Тоҷикӣ',
  },
  {
    label: 'Tamil (தமிழ்)',
    code: 'ta',
    model: 'nano',
    country_code: 'IN',
    short_label: 'தமிழ்',
  },
  {
    label: 'Tatar (татар)',
    code: 'tt',
    model: 'nano',
    country_code: 'RU',
    short_label: 'татар',
  },
  {
    label: 'Telugu (తెలుగు)',
    code: 'te',
    model: 'nano',
    country_code: 'IN',
    short_label: 'తెలుగు',
  },
  {
    label: 'Thai (ไทย)',
    code: 'th',
    model: 'nano',
    country_code: 'TH',
    short_label: 'ไทย',
  },
  {
    label: 'Tibetan (བོད་ཡིག)',
    code: 'bo',
    model: 'nano',
    country_code: 'CN',
    short_label: 'བོད་ཡིག',
  },
  {
    label: 'Turkmen (Türkmen)',
    code: 'tk',
    model: 'nano',
    country_code: 'TM',
    short_label: 'Türkmen',
  },
  {
    label: 'Urdu (اردو)',
    code: 'ur',
    model: 'nano',
    country_code: 'PK',
    short_label: 'اردو',
  },
  {
    label: 'Uzbek (Oʻzbek)',
    code: 'uz',
    model: 'nano',
    country_code: 'UZ',
    short_label: 'Oʻzbek',
  },
  {
    label: 'Welsh (Cymraeg)',
    code: 'cy',
    model: 'nano',
    country_code: 'GB',
    short_label: 'Cymraeg',
  },
  {
    label: 'Yiddish (ייִדיש)',
    code: 'yi',
    model: 'nano',
    country_code: 'IL',
    short_label: 'ייִדיש',
  },
  {
    label: 'Yoruba (Yorùbá)',
    code: 'yo',
    model: 'nano',
    country_code: 'NG',
    short_label: 'Yorùbá',
  },
];
