import {languageType} from 'components/LanguageSelector';

export const languages_best: languageType[] = [
  {
    label: 'English (Global English)',
    code: 'en',
    model: 'best',
    country_code: 'GB',
    short_label: 'English',
  },
  {
    label: 'English (Australia)',
    code: 'en_au',
    model: 'best',
    country_code: 'AU',
    short_label: 'English',
  },
  {
    label: 'English (United Kingdom)',
    code: 'en_uk',
    model: 'best',
    country_code: 'GB',
    short_label: 'English',
  },
  {
    label: 'English (United States)',
    code: 'en_us',
    model: 'best',
    country_code: 'US',
    short_label: 'English',
  },
  {
    label: 'Spanish (Español)',
    code: 'es',
    model: 'best',
    country_code: 'ES',
    short_label: 'Español',
  },
  {
    label: 'French (Français)',
    code: 'fr',
    model: 'best',
    country_code: 'FR',
    short_label: 'Français',
  },
  {
    label: 'German (Deutsch)',
    code: 'de',
    model: 'best',
    country_code: 'DE',
    short_label: 'Deutsch',
  },
  {
    label: 'Italian (Italiano)',
    code: 'it',
    model: 'best',
    country_code: 'IT',
    short_label: 'Italiano',
  },
  {
    label: 'Portuguese (Português)',
    code: 'pt',
    model: 'best',
    country_code: 'PT',
    short_label: 'Português',
  },
  {
    label: 'Dutch (Nederlands)',
    code: 'nl',
    model: 'best',
    country_code: 'NL',
    short_label: 'Nederlands',
  },
  {
    label: 'Hindi (हिन्दी)',
    code: 'hi',
    model: 'best',
    country_code: 'IN',
    short_label: 'हिन्दी',
  },
  {
    label: 'Japanese (日本語)',
    code: 'ja',
    model: 'best',
    country_code: 'JP',
    short_label: '日本語',
  },
  {
    label: 'Chinese (中文)',
    code: 'zh',
    model: 'best',
    country_code: 'CN',
    short_label: '中文',
  },
  {
    label: 'Finnish (Suomi)',
    code: 'fi',
    model: 'best',
    country_code: 'FI',
    short_label: 'Suomi',
  },
  {
    label: 'Korean (한국어)',
    code: 'ko',
    model: 'best',
    country_code: 'KR',
    short_label: '한국어',
  },
  {
    label: 'Polish (Polski)',
    code: 'pl',
    model: 'best',
    country_code: 'PL',
    short_label: 'Polski',
  },
  {
    label: 'Russian (Русский)',
    code: 'ru',
    model: 'best',
    country_code: 'RU',
    short_label: 'Русский',
  },
  {
    label: 'Turkish (Türkçe)',
    code: 'tr',
    model: 'best',
    country_code: 'TR',
    short_label: 'Türkçe',
  },
  {
    label: 'Ukrainian (Українська)',
    code: 'uk',
    model: 'best',
    country_code: 'UA',
    short_label: 'Українська',
  },
  {
    label: 'Vietnamese (Tiếng Việt)',
    code: 'vi',
    model: 'best',
    country_code: 'VN',
    short_label: 'Tiếng Việt',
  },
];
